// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package com.basho.search.proto;

public final class Analysis {
  private Analysis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AnalysisRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisRequest.newBuilder() to construct.
    private AnalysisRequest() {
      initFields();
    }
    private AnalysisRequest(boolean noInit) {}
    
    private static final AnalysisRequest defaultInstance;
    public static AnalysisRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable;
    }
    
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasText) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasText()) {
        output.writeString(1, getText());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisRequest result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisRequest();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisRequest.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisRequest getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisRequest) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisRequest other) {
        if (other == com.basho.search.proto.Analysis.AnalysisRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setText(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string text = 1;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisRequest)
    }
    
    static {
      defaultInstance = new AnalysisRequest(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisRequest)
  }
  
  public static final class AnalysisError extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisError.newBuilder() to construct.
    private AnalysisError() {
      initFields();
    }
    private AnalysisError(boolean noInit) {}
    
    private static final AnalysisError defaultInstance;
    public static AnalysisError getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisError getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisError_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable;
    }
    
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional int32 error_number = 3;
    public static final int ERROR_NUMBER_FIELD_NUMBER = 3;
    private boolean hasErrorNumber;
    private int errorNumber_ = 0;
    public boolean hasErrorNumber() { return hasErrorNumber; }
    public int getErrorNumber() { return errorNumber_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessage()) {
        output.writeString(1, getMessage());
      }
      if (hasDescription()) {
        output.writeString(2, getDescription());
      }
      if (hasErrorNumber()) {
        output.writeInt32(3, getErrorNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMessage());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDescription());
      }
      if (hasErrorNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getErrorNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisError result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisError.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisError();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisError internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisError();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisError.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisError getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisError.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisError build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisError buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisError buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisError returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisError) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisError other) {
        if (other == com.basho.search.proto.Analysis.AnalysisError.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasErrorNumber()) {
          setErrorNumber(other.getErrorNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setMessage(input.readString());
              break;
            }
            case 18: {
              setDescription(input.readString());
              break;
            }
            case 24: {
              setErrorNumber(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string message = 1;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // optional string description = 2;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // optional int32 error_number = 3;
      public boolean hasErrorNumber() {
        return result.hasErrorNumber();
      }
      public int getErrorNumber() {
        return result.getErrorNumber();
      }
      public Builder setErrorNumber(int value) {
        result.hasErrorNumber = true;
        result.errorNumber_ = value;
        return this;
      }
      public Builder clearErrorNumber() {
        result.hasErrorNumber = false;
        result.errorNumber_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisError)
    }
    
    static {
      defaultInstance = new AnalysisError(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisError)
  }
  
  public static final class AnalysisResult extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisResult.newBuilder() to construct.
    private AnalysisResult() {
      initFields();
    }
    private AnalysisResult(boolean noInit) {}
    
    private static final AnalysisResult defaultInstance;
    public static AnalysisResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable;
    }
    
    // optional string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private boolean hasToken;
    private java.lang.String token_ = "";
    public boolean hasToken() { return hasToken; }
    public java.lang.String getToken() { return token_; }
    
    // required int32 done = 2;
    public static final int DONE_FIELD_NUMBER = 2;
    private boolean hasDone;
    private int done_ = 0;
    public boolean hasDone() { return hasDone; }
    public int getDone() { return done_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDone) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasToken()) {
        output.writeString(1, getToken());
      }
      if (hasDone()) {
        output.writeInt32(2, getDone());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasToken()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getToken());
      }
      if (hasDone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getDone());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisResult result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisResult();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisResult.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisResult getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisResult) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisResult other) {
        if (other == com.basho.search.proto.Analysis.AnalysisResult.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setToken(input.readString());
              break;
            }
            case 16: {
              setDone(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string token = 1;
      public boolean hasToken() {
        return result.hasToken();
      }
      public java.lang.String getToken() {
        return result.getToken();
      }
      public Builder setToken(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasToken = true;
        result.token_ = value;
        return this;
      }
      public Builder clearToken() {
        result.hasToken = false;
        result.token_ = getDefaultInstance().getToken();
        return this;
      }
      
      // required int32 done = 2;
      public boolean hasDone() {
        return result.hasDone();
      }
      public int getDone() {
        return result.getDone();
      }
      public Builder setDone(int value) {
        result.hasDone = true;
        result.done_ = value;
        return this;
      }
      public Builder clearDone() {
        result.hasDone = false;
        result.done_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisResult)
    }
    
    static {
      defaultInstance = new AnalysisResult(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016analysis.proto\022\025basho.search.analysis\"" +
      "\037\n\017AnalysisRequest\022\014\n\004text\030\001 \002(\t\"K\n\rAnal" +
      "ysisError\022\017\n\007message\030\001 \002(\t\022\023\n\013descriptio" +
      "n\030\002 \001(\t\022\024\n\014error_number\030\003 \001(\005\"-\n\016Analysi" +
      "sResult\022\r\n\005token\030\001 \001(\t\022\014\n\004done\030\002 \002(\005B\030\n\026" +
      "com.basho.search.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_basho_search_analysis_AnalysisRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisRequest_descriptor,
              new java.lang.String[] { "Text", },
              com.basho.search.proto.Analysis.AnalysisRequest.class,
              com.basho.search.proto.Analysis.AnalysisRequest.Builder.class);
          internal_static_basho_search_analysis_AnalysisError_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisError_descriptor,
              new java.lang.String[] { "Message", "Description", "ErrorNumber", },
              com.basho.search.proto.Analysis.AnalysisError.class,
              com.basho.search.proto.Analysis.AnalysisError.Builder.class);
          internal_static_basho_search_analysis_AnalysisResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisResult_descriptor,
              new java.lang.String[] { "Token", "Done", },
              com.basho.search.proto.Analysis.AnalysisResult.class,
              com.basho.search.proto.Analysis.AnalysisResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
