// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package com.basho.search.proto;

public final class Analysis {
  private Analysis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AnalysisRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisRequest.newBuilder() to construct.
    private AnalysisRequest() {
      initFields();
    }
    private AnalysisRequest(boolean noInit) {}
    
    private static final AnalysisRequest defaultInstance;
    public static AnalysisRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable;
    }
    
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // optional string analyzer_factory = 2;
    public static final int ANALYZER_FACTORY_FIELD_NUMBER = 2;
    private boolean hasAnalyzerFactory;
    private java.lang.String analyzerFactory_ = "";
    public boolean hasAnalyzerFactory() { return hasAnalyzerFactory; }
    public java.lang.String getAnalyzerFactory() { return analyzerFactory_; }
    
    // repeated string analyzer_args = 3;
    public static final int ANALYZER_ARGS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.String> analyzerArgs_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getAnalyzerArgsList() {
      return analyzerArgs_;
    }
    public int getAnalyzerArgsCount() { return analyzerArgs_.size(); }
    public java.lang.String getAnalyzerArgs(int index) {
      return analyzerArgs_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasText) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasText()) {
        output.writeString(1, getText());
      }
      if (hasAnalyzerFactory()) {
        output.writeString(2, getAnalyzerFactory());
      }
      for (java.lang.String element : getAnalyzerArgsList()) {
        output.writeString(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      if (hasAnalyzerFactory()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getAnalyzerFactory());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getAnalyzerArgsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getAnalyzerArgsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisRequest result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisRequest();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisRequest.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisRequest getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.analyzerArgs_ != java.util.Collections.EMPTY_LIST) {
          result.analyzerArgs_ =
            java.util.Collections.unmodifiableList(result.analyzerArgs_);
        }
        com.basho.search.proto.Analysis.AnalysisRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisRequest) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisRequest other) {
        if (other == com.basho.search.proto.Analysis.AnalysisRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasAnalyzerFactory()) {
          setAnalyzerFactory(other.getAnalyzerFactory());
        }
        if (!other.analyzerArgs_.isEmpty()) {
          if (result.analyzerArgs_.isEmpty()) {
            result.analyzerArgs_ = new java.util.ArrayList<java.lang.String>();
          }
          result.analyzerArgs_.addAll(other.analyzerArgs_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setText(input.readString());
              break;
            }
            case 18: {
              setAnalyzerFactory(input.readString());
              break;
            }
            case 26: {
              addAnalyzerArgs(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string text = 1;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // optional string analyzer_factory = 2;
      public boolean hasAnalyzerFactory() {
        return result.hasAnalyzerFactory();
      }
      public java.lang.String getAnalyzerFactory() {
        return result.getAnalyzerFactory();
      }
      public Builder setAnalyzerFactory(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAnalyzerFactory = true;
        result.analyzerFactory_ = value;
        return this;
      }
      public Builder clearAnalyzerFactory() {
        result.hasAnalyzerFactory = false;
        result.analyzerFactory_ = getDefaultInstance().getAnalyzerFactory();
        return this;
      }
      
      // repeated string analyzer_args = 3;
      public java.util.List<java.lang.String> getAnalyzerArgsList() {
        return java.util.Collections.unmodifiableList(result.analyzerArgs_);
      }
      public int getAnalyzerArgsCount() {
        return result.getAnalyzerArgsCount();
      }
      public java.lang.String getAnalyzerArgs(int index) {
        return result.getAnalyzerArgs(index);
      }
      public Builder setAnalyzerArgs(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.analyzerArgs_.set(index, value);
        return this;
      }
      public Builder addAnalyzerArgs(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.analyzerArgs_.isEmpty()) {
          result.analyzerArgs_ = new java.util.ArrayList<java.lang.String>();
        }
        result.analyzerArgs_.add(value);
        return this;
      }
      public Builder addAllAnalyzerArgs(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.analyzerArgs_.isEmpty()) {
          result.analyzerArgs_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.analyzerArgs_);
        return this;
      }
      public Builder clearAnalyzerArgs() {
        result.analyzerArgs_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisRequest)
    }
    
    static {
      defaultInstance = new AnalysisRequest(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisRequest)
  }
  
  public static final class AnalysisStop extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisStop.newBuilder() to construct.
    private AnalysisStop() {
      initFields();
    }
    private AnalysisStop(boolean noInit) {}
    
    private static final AnalysisStop defaultInstance;
    public static AnalysisStop getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisStop getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisStop_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisStop_fieldAccessorTable;
    }
    
    // optional int32 wait = 1;
    public static final int WAIT_FIELD_NUMBER = 1;
    private boolean hasWait;
    private int wait_ = 0;
    public boolean hasWait() { return hasWait; }
    public int getWait() { return wait_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasWait()) {
        output.writeInt32(1, getWait());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasWait()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getWait());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisStop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisStop prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisStop result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisStop.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisStop();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisStop internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisStop();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisStop.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisStop getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisStop.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisStop build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisStop buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisStop buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisStop returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisStop) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisStop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisStop other) {
        if (other == com.basho.search.proto.Analysis.AnalysisStop.getDefaultInstance()) return this;
        if (other.hasWait()) {
          setWait(other.getWait());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setWait(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 wait = 1;
      public boolean hasWait() {
        return result.hasWait();
      }
      public int getWait() {
        return result.getWait();
      }
      public Builder setWait(int value) {
        result.hasWait = true;
        result.wait_ = value;
        return this;
      }
      public Builder clearWait() {
        result.hasWait = false;
        result.wait_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisStop)
    }
    
    static {
      defaultInstance = new AnalysisStop(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisStop)
  }
  
  public static final class AnalysisError extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisError.newBuilder() to construct.
    private AnalysisError() {
      initFields();
    }
    private AnalysisError(boolean noInit) {}
    
    private static final AnalysisError defaultInstance;
    public static AnalysisError getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisError getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisError_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable;
    }
    
    // required string error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private boolean hasError;
    private java.lang.String error_ = "";
    public boolean hasError() { return hasError; }
    public java.lang.String getError() { return error_; }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional int32 error_number = 3;
    public static final int ERROR_NUMBER_FIELD_NUMBER = 3;
    private boolean hasErrorNumber;
    private int errorNumber_ = 0;
    public boolean hasErrorNumber() { return hasErrorNumber; }
    public int getErrorNumber() { return errorNumber_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasError) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasError()) {
        output.writeString(1, getError());
      }
      if (hasDescription()) {
        output.writeString(2, getDescription());
      }
      if (hasErrorNumber()) {
        output.writeInt32(3, getErrorNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasError()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getError());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDescription());
      }
      if (hasErrorNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getErrorNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisError result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisError.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisError();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisError internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisError();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisError.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisError getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisError.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisError build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisError buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisError buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisError returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisError) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisError other) {
        if (other == com.basho.search.proto.Analysis.AnalysisError.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasErrorNumber()) {
          setErrorNumber(other.getErrorNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setError(input.readString());
              break;
            }
            case 18: {
              setDescription(input.readString());
              break;
            }
            case 24: {
              setErrorNumber(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string error = 1;
      public boolean hasError() {
        return result.hasError();
      }
      public java.lang.String getError() {
        return result.getError();
      }
      public Builder setError(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasError = true;
        result.error_ = value;
        return this;
      }
      public Builder clearError() {
        result.hasError = false;
        result.error_ = getDefaultInstance().getError();
        return this;
      }
      
      // optional string description = 2;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // optional int32 error_number = 3;
      public boolean hasErrorNumber() {
        return result.hasErrorNumber();
      }
      public int getErrorNumber() {
        return result.getErrorNumber();
      }
      public Builder setErrorNumber(int value) {
        result.hasErrorNumber = true;
        result.errorNumber_ = value;
        return this;
      }
      public Builder clearErrorNumber() {
        result.hasErrorNumber = false;
        result.errorNumber_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisError)
    }
    
    static {
      defaultInstance = new AnalysisError(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisError)
  }
  
  public static final class AnalysisResult extends
      com.google.protobuf.GeneratedMessage {
    // Use AnalysisResult.newBuilder() to construct.
    private AnalysisResult() {
      initFields();
    }
    private AnalysisResult(boolean noInit) {}
    
    private static final AnalysisResult defaultInstance;
    public static AnalysisResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public AnalysisResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.basho.search.proto.Analysis.internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable;
    }
    
    // optional string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private boolean hasToken;
    private java.lang.String token_ = "";
    public boolean hasToken() { return hasToken; }
    public java.lang.String getToken() { return token_; }
    
    // required int32 done = 2;
    public static final int DONE_FIELD_NUMBER = 2;
    private boolean hasDone;
    private int done_ = 0;
    public boolean hasDone() { return hasDone; }
    public int getDone() { return done_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDone) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasToken()) {
        output.writeString(1, getToken());
      }
      if (hasDone()) {
        output.writeInt32(2, getDone());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasToken()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getToken());
      }
      if (hasDone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getDone());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.basho.search.proto.Analysis.AnalysisResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.basho.search.proto.Analysis.AnalysisResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.basho.search.proto.Analysis.AnalysisResult result;
      
      // Construct using com.basho.search.proto.Analysis.AnalysisResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.basho.search.proto.Analysis.AnalysisResult();
        return builder;
      }
      
      protected com.basho.search.proto.Analysis.AnalysisResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.basho.search.proto.Analysis.AnalysisResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.basho.search.proto.Analysis.AnalysisResult.getDescriptor();
      }
      
      public com.basho.search.proto.Analysis.AnalysisResult getDefaultInstanceForType() {
        return com.basho.search.proto.Analysis.AnalysisResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.basho.search.proto.Analysis.AnalysisResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.basho.search.proto.Analysis.AnalysisResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.basho.search.proto.Analysis.AnalysisResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.basho.search.proto.Analysis.AnalysisResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.basho.search.proto.Analysis.AnalysisResult) {
          return mergeFrom((com.basho.search.proto.Analysis.AnalysisResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.basho.search.proto.Analysis.AnalysisResult other) {
        if (other == com.basho.search.proto.Analysis.AnalysisResult.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setToken(input.readString());
              break;
            }
            case 16: {
              setDone(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string token = 1;
      public boolean hasToken() {
        return result.hasToken();
      }
      public java.lang.String getToken() {
        return result.getToken();
      }
      public Builder setToken(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasToken = true;
        result.token_ = value;
        return this;
      }
      public Builder clearToken() {
        result.hasToken = false;
        result.token_ = getDefaultInstance().getToken();
        return this;
      }
      
      // required int32 done = 2;
      public boolean hasDone() {
        return result.hasDone();
      }
      public int getDone() {
        return result.getDone();
      }
      public Builder setDone(int value) {
        result.hasDone = true;
        result.done_ = value;
        return this;
      }
      public Builder clearDone() {
        result.hasDone = false;
        result.done_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:basho.search.analysis.AnalysisResult)
    }
    
    static {
      defaultInstance = new AnalysisResult(true);
      com.basho.search.proto.Analysis.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:basho.search.analysis.AnalysisResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisStop_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisStop_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_basho_search_analysis_AnalysisResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016analysis.proto\022\025basho.search.analysis\"" +
      "P\n\017AnalysisRequest\022\014\n\004text\030\001 \002(\t\022\030\n\020anal" +
      "yzer_factory\030\002 \001(\t\022\025\n\ranalyzer_args\030\003 \003(" +
      "\t\"\034\n\014AnalysisStop\022\014\n\004wait\030\001 \001(\005\"I\n\rAnaly" +
      "sisError\022\r\n\005error\030\001 \002(\t\022\023\n\013description\030\002" +
      " \001(\t\022\024\n\014error_number\030\003 \001(\005\"-\n\016AnalysisRe" +
      "sult\022\r\n\005token\030\001 \001(\t\022\014\n\004done\030\002 \002(\005B\030\n\026com" +
      ".basho.search.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_basho_search_analysis_AnalysisRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_basho_search_analysis_AnalysisRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisRequest_descriptor,
              new java.lang.String[] { "Text", "AnalyzerFactory", "AnalyzerArgs", },
              com.basho.search.proto.Analysis.AnalysisRequest.class,
              com.basho.search.proto.Analysis.AnalysisRequest.Builder.class);
          internal_static_basho_search_analysis_AnalysisStop_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_basho_search_analysis_AnalysisStop_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisStop_descriptor,
              new java.lang.String[] { "Wait", },
              com.basho.search.proto.Analysis.AnalysisStop.class,
              com.basho.search.proto.Analysis.AnalysisStop.Builder.class);
          internal_static_basho_search_analysis_AnalysisError_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_basho_search_analysis_AnalysisError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisError_descriptor,
              new java.lang.String[] { "Error", "Description", "ErrorNumber", },
              com.basho.search.proto.Analysis.AnalysisError.class,
              com.basho.search.proto.Analysis.AnalysisError.Builder.class);
          internal_static_basho_search_analysis_AnalysisResult_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_basho_search_analysis_AnalysisResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_basho_search_analysis_AnalysisResult_descriptor,
              new java.lang.String[] { "Token", "Done", },
              com.basho.search.proto.Analysis.AnalysisResult.class,
              com.basho.search.proto.Analysis.AnalysisResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
